Feature/fix for building using clang
philips-software/embeddedinfralib pull request #49
Opened 2022-03-09 20:53 UTC by daantimmer

For more information w.r.t. to the default initialization issue in UartWindows.hpp, see: https://godbolt.org/z/E7qGE375K

2022-03-11 12:03 UTC, richardapeters approved these changes

2022-03-15 08:28 UTC, rjaegers requested changes
Can you add the clang build to the GitHub Actions CI system as well? This will make sure we don't break the Clang build in the future going forward.

2022-03-15 08:28 UTC, rjaegers commented on hal/windows/UartWindows.hpp
> +            UartWindowsConfig(){}
Can you add a space please.

```suggestion
            UartWindowsConfig() {}
```

2022-03-16 09:35 UTC, daantimmer commented
Discussed with @rjaegers to not add a clang-based windows build to CI as the work required and the additional build time is not worth it. the macos build is already using the clang compiler. This would only add coverage for a few files only used on windows only builds.

2022-03-16 10:14 UTC, rjaegers approved these changes

2022-03-16 10:16 UTC, merged